version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://192.168.1.241:5000

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=c##a_user
      - DB_PASSWORD=password
      - DB_HOST=192.168.1.241
      - DB_PORT=1521
      - DB_SERVICE=xe
